### ISSUE TITLE
Confirming Questions

### ISSUE THREAD

**Issue by giangbimin** [giangbimin/gscaper#1]
### 1. Does the application need to store the CSV file for each request, it's help me to create ideas for designing the database?

- If storage isn't required, we create a single model: `ScraperResult(keyword, result, ...)`. Data is parsed directly in the controller, create  ScraperRequest record the run sidekiq to scraper each one cached with Redis. 
- If storing the user's request and file in the system is necessary, I propose a solution: `ScraperRequest` with a CSV file via `activate_storage`. In the Sidekiq worker, we use this record to create multiple `ScraperResult` instances, and then asynchronously run the scraper for each.

### 2.Do I have to implement authentication features without using a gem?
- Can I use the Devise Gem, considering its stability, as we won't need to test it again?
- Or have to build the authentication logic from scratch

### 3. Is it acceptable to implement the Google scraper services by creating a local gem for it?
- Since it's a stateless service, we don't need to require Ruby on Rails to test it.

### 4. I'm attempting to implement a scraper logic with Sidekiq for asynchronous background jobs. give me a comment.

- Start multiple workers, each with a unique IP.
- Define various user-agents for multiple requests.
- Implement a run limit of 10 jobs per minute using Sidekiq's `perform_in((x * 10).seconds)` to adhere to Google's rate limit.
- Determine the available resources in terms of worker instances and IPs.

### 5.If (4) encounters a block, may I use Google Search cache to replace the result?

If blocked, consider using:

```
"http://webcache.googleusercontent.com/search?q=cache:" at the beginning, followed by the Google URL after "cache https://www.google.com/search?q=footabll&gl=us&tbm=isch."
For example, "https://webcache.googleusercontent.com/search?q=cache:https://www.google.com/search?q=footabll&gl=us&tbm=isch"
```

### 6. If I have to cache the result of a Google search?
- how often should we revalidate and refresh the data?
- because of given that the first page of Google search results usually changes.

### 7. Due to the use of workers for this assignment, are there not many web services providers that allow us to run web and worker instances for free?
- may i can create a dockerfile for production and docker-composer file instead to replace the deployment requirement

**Comment by longnd** [comment]
Hi Giang
I'm Long - an engineering lead from Nimble, and I'm in charge of the code review for this code challenge.

Let's me answer your questions:

1. Does the application need to store the CSV file for each request, it's help me to create ideas for designing the database?
There are no specific requirements regarding storing the CSV file. Therefore, let's assess the best approach for the application you're building by evaluating the pros and cons of each solution. Consider whether storing the file will bring any benefits and if it is worth the added complexity. Additionally, choose an approach that makes sense given the timeline of the code challenge (a week). I can't provide a concrete answer since we also need to evaluate how each candidate analyzes the requirement and picks the right technical choices for implementation.

2. Do I have to implement authentication features without using a gem?
Again, there is no specific requirement regarding the technical choice. Please assets the requirements just like a normal application, which solution will you choose: picking a well-known library or implementing it on your own? We look forward to understanding your technical choice.

3. Is it acceptable to implement the Google scraper services by creating a local gem for it?
Since it relates to the application architecture, I leave it to you to decide the best approach for the application, we don't have a requirement for it to be part of the application for a local gem.

4, 5 & 6
Since they are too detailed into the implementation, I can't give exact suggestions. As mentioned before, some parts of the requirements are not extra clear, allowing each candidate to analyze and choose an implementation that makes sense and showcases their skills. As a general tip, unless there is a specific requirement to follow, such as merging code through a pull request, you are free to choose and implement what you believe makes sense and fulfills the key requirements. For example, how to work around the rate limit of Google. Additionally, you need to consider the development effort within the given timeline of one week. While the main focus is on the core business domain of uploading files and scraping results, a fully implemented application with all features and thorough testing is also expected.

7 Due to the use of workers for this assignment, are there not many web services providers that allow us to run web and worker instances for free?
While it would be ideal to have the application deployed, but if you found the implementation is too complex to be deployable on a normal service (e.g. Fly.io supports worker service), a dockerized application is also good.

happy coding.
