### ISSUE TITLE
Improve source code organization

### ISSUE THREAD

**Issue by longnd** [giangbimin/gscaper#16]
## Issue
Some parts of the code weren't well organized. Examples:
- The part of the code to handle uploaded CSV file, parsing, storing into DB before enqueuing as background jobs used 2 services `app/services/user_keywords_service.rb` & `csv_keywords_parser_service.rb`. In this case, it is a good use case for form objects. Then the code looks cleaner
- https://www.mintbit.com/blog/understanding-the-differences-traditional-forms-vs-form-objects-in-rails
- https://thoughtbot.com/ruby-science/introduce-form-object.html

Here is a simple implementation
```ruby
# app/forms/csv_keyword_form.rb

class CsvKeywordsForm
  include ActiveModel::Model
  validates_with CsvFileValidator # use custom validator to validate the keyword file: must be present, must be CSV format, have up to 100 keywords

  attr_reader :file, :user, :keyword_ids

  def initialize(user)
    @user = user
  end

  def save(file)
    @file = file

    return false unless valid? 

    save_keywords
    errors.empty?
  end

  private

  def save_keywords
    # parse keyword file
    # save keywords into DB
  end
end

```
Then use it in the controller as
```ruby
class KeywordsController < ApplicationController
  #...

  def create
    if save_keywords_from_file
      KeywordScraperJob.perform_in(...)
      flash[:notice] = I18n.t('keyword file uploaded successfully')
    else
      flash[:alert] = csv_form.errors.full_messages.first
    end
    redirect_to keywords_path
  end

  private

  def save_keywords_from_file
    csv_form.save(params[:file])
  end

  def csv_form
    @csv_form ||= CsvKeywordsForm.new(current_user)
  end
end
```

- `services/job/keyword_scraper_service.rb`
  Having a service scoped under the `job` directory is odd. Shouldn't it be scoped by the domain, e.g. `keyword/scapper_service.rb` instead?

**Comment by giangbimin** [comment]
@longnd 
### actually in understand how to use form object service but i don't really like to use it because of these reasons

- have to use activate-record to handle validate with 3 layers: form + model + db
- don't bring many design patterns in a same project
- more complexity

### the reason i use 2 services are
- one is validate to more clearly without activate-record
- another one to handle transaction and and db

### i'll implement it for this feature, thanks for your suggestions

**Comment by giangbimin** [comment]
@longnd
- I think design patterns provide proven solutions to common problems. 

I completely agree with it, and it depends on the use case. I typically take the time to thoroughly design and understand the problem before implementing the code. For the majority of use cases, I prefer creating simple and straightforward logic for each scenario to facilitate ease of implementation and testing. I don't often apply many design patterns within the same project.


- terms of complexity. 

I've had some negative experiences in this regard. In the past, I applied complex models and nested relationships, which made debugging challenging due to the numerous layers involved. For instance, when dealing with a transaction to save a form where a post has many comments, errors originating from comment validations could be confusing because comments are not direct elements of the form.To mitigate this, I've developed a habit of using service objects for quick data validation instead of relying solely on ActiveModel::Model validation. This approach simplifies the process in certain use cases and aligns with my preference for keeping things as straightforward as possible.


 # this is the implement using form object and validators

https://github.com/giangbimin/gscaper/pull/21/files
